#Bed Dupe 3.0 Official
#Bed Dupe es un plugin con el que se duplica con camas 
#tambien hay un porcentaje en la cual puedes bariar segun la economia de tu server

probability-percentage: 100

#Command Reload "/beddupereload"

#UNA cosa mas que aclarar este es mi propio 
#codigo AnarchyGooD pero eres libre puedes hacer lo que quieras