name: BedDupe
version: ${project.version}
main: me.akaishin.beddup.BedDupe
api-version: 1.12.2
authors: [ akaishin ]
description: plugin de dupeo con camas brutal
commands:
  beddupereload:
    usage: /beddupereload